config/routes.rb
Rails.application.routes.draw do

  get 'session/new'
  root :to => 'pages#home'

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

  get '/users/edit' => 'users#edit'
  
  resources :users, :only => [:index, :new, :show, :create, :update]

  resources :tweets, :only => [:new, :create, :destroy]

  resources :relationships, :only => [:new, :create, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/relationship.rb
class Relationship < ApplicationRecord

  belongs_to :follower, class_name: "User", :optional => true
  belongs_to :followed, class_name: "User", :optional => true

end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user, :optional => true
end

app/models/user.rb
class User < ApplicationRecord

  has_secure_password
  validates :email, :presence => true, :uniqueness => true

  has_many :tweets, dependent: :destroy
  has_many :relationships, foreign_key: "follower_id", dependent: :destroy
  has_many :followed_users, through: :relationships, source: :followed

  after_create :follow_yourself

  private
    def follow_yourself
      @relationship = Relationship.create :followed_id => self.id, :follower_id => self.id
      self.relationships << @relationship
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :fetch_user

  private
  def fetch_user
    @current_user = User.find_by :id => session[:user_id] if session[:user_id].present?
    session[:user_id] = nil unless @current_user.present?
  end

  def check_for_login
    redirect_to login_path unless @current_user.present?
  end

  def check_for_admin
    redirect_to root_path unless (@current_user.present? && @current_user.admin?)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    if @current_user.present?
      @tweets = Tweet.all.where(user_id: @current_user.followed_users).reverse
    else
      redirect_to login_path
    end
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

def new
  @relationship = Relationship.new
end

def create
  @relationship = Relationship.create :followed_id => params[:followed_id], :follower_id => @current_user.id
  @current_user.relationships << @relationship
end

end

app/controllers/session_controller.rb
class SessionController < ApplicationController

  def new
  end

  def create
    user = User.find_by :email => params[:email]
    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      flash[:error_message] = "Invalid email or password"
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_path
  end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  def show
    @tweets = Tweet.all
  end

  def create
    tweet = Tweet.create tweet_params
    @current_user.tweets << tweet
  # or @current_user.mixtapes.create << this works without  "optional true"
    redirect_to root_path
  end

  def destroy
    tweet = Tweet.find params[:id]
    tweet.destroy
    redirect_to root_path
  end

  private
  def tweet_params
    params.require(:tweet).permit(:content)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  #before_action :check_for_admin, :only => [:index]

  def index
    @users = User.all
  end

  def show
    @user = User.find params[:id]
  end

  def new
    @user = User.new
  end

  def create

    @user = User.new user_params
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @user = @current_user
  end

  def update
    User.update user_params
    redirect_to user_path
  end

  private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :handle, :name, :image, :bio)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tweetstack</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  </head>

  <body>
  <div class="container">
    <nav>
      <% if @current_user.present? %>
      <h5><%= link_to "Home", root_path %></h5>
      <h5><%= link_to "Users", users_path if @current_user.admin? %></h5>
      <h5><%= link_to "Edit Profile", users_edit_path %></h5>
      <h5><%= link_to "Logout", login_path, :method => 'delete' %></h5>
      <% else %>
      <%= link_to "Sign up", new_user_path %>
      <%= link_to "Sign in", login_path %>
    <% end %>
    </nav>
    <%= yield %>
  </div>

  </body>
</html>

app/views/pages/home.html.erb
<div class="row">
  <div class="col-3" id="left-column">
    <img src="https://static01.nyt.com/images/2014/08/10/magazine/10wmt/10wmt-superJumbo-v4.jpg" alt="" class="logo-thumb">
  </div>
  <div class="col-5" id="middle-column">
    <h4>Home</h4>
    <%= form_for Tweet.new do |f| %>
    <%= f.text_area :content, :wrap => "hard", :class => "tweet-input", :placeholder => "What's happening?"%>
    <div class="tweet-button">
      <%= f.submit "tweet", :class => "btn btn-primary" %>
    </div>
    <% end %>

    <div class="tweet-container">

      <% @tweets.each do |tweet|  %>
      <div class="tweet">
      <hr>
        <div class="row">
          <div class="col-2">
            <img src="<%= tweet.user.image %>" alt="" class="tweet-thumb">
          </div>
          <div class="col-10">
            <div class="top-line">
              <p id="tweet-author"><%= tweet.user.name %></p>
            </div>
            <p><%= tweet.content %></p>
            <% if tweet.user == @current_user %>
            <%= button_to 'delete', tweet_path(tweet.id), :method => 'delete', :class => 'btn-danger' %>
            <% end %>
          </div>
        </div>
      </div>

      <% end %>

    </div>

  </div>
  <div class="col-4">
    <h4>Who to follow</h4>
    <% User.all.each do |user| %>
      <% if user != @current_user %>
        <div class="row">
          <div class="col-3">
            <img src="<%= user.image %>" alt="" class="follow-thumb">
          </div>
          <div class="col-9">
            <%= user.name %>
            <%= button_to 'Follow', relationships_path, :method => 'post', :params => { :followed_id => user.id}, :class => "btn-primary" %>
          </div>
          <hr>
        </div>
      <% end %>
    <% end %>
  </div>

</div>

app/views/session/new.html.erb
<h1>Sign In</h1>

<% if flash[:error_message] %>
  <p><%= flash[:error_message] %></p>
<% end %>

<%= form_tag login_path do %>
  <%= label_tag :email %>
  <%= email_field_tag :email %>

  <%= label_tag :password %>
  <%= password_field_tag :password %>

  <%= submit_tag "Sign In" %>
<% end %>

app/views/users/edit.html.erb
  <%= form_for @current_user do |f|%>
    <div class="form-group">
      <%= f.label :email %>
      <%= f.email_field :email, :value => @user.email, :class => "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :bio %>
      <%= f.text_field :bio, :value => @user.bio, :class => "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, :value => @user.name,:class => "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :image %>
      <%= f.text_field :image, :value => @user.image, :class => "form-control" %>
    </div>
    <%= f.submit "Update Profile", :class => "btn-primary" %>
  <% end %>

app/views/users/index.html.erb
<h1>All Users</h1>

<% @users.each do |user| %>

    <p><%= user.email %></p>
    <%= button_to 'Follow', relationships_path, :method => 'post', :params => { :followed_id => user.id} %>

<% end %>

app/views/users/new.html.erb
<h1>Create your account</h1>

<% if @user.errors.any? %>
<ol>
  <% @user.errors.full_messages.each do |msg| %>
  <li class="sign-up-error"><%= msg %></li>
  <% end %>
</ol>
<% end %>

<%= form_for @user do |f| %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit "Sign Up" %>
<% end %>

app/views/users/show.html.erb
<div class="row">

  <div class="col-3" id="left-column">

  </div>

  <div class="col-5" id="middle-column">
    <img src="<%= @user.image %>" alt="" class="profile-image">
    <h4 class="profile-name"><%= @user.name %></h4>
    <p class="bio"><%= @user.bio %></p>
    <p class="profile-subheading">Tweets</p>

    <% @user.tweets.each do |tweet| %>
    <div class="row">
      <div class="col-2">
        <img src="<%= tweet.user.image %>" alt="" class="tweet-thumb">
      </div>
      <div class="col-10">
        <div class="top-line">
          <p id="tweet-author"><%= link_to "<%= tweet.user.name %>", user_path %></p>
        </div>
        <p><%= tweet.content %></p>
        <% if tweet.user == @current_user %>
        <%= button_to 'delete', tweet_path(tweet.id), :method => 'delete', :class => 'btn-danger' %>
        <% end %>
      </div>
    </div>
    <hr>
    <% end %>
  </div>

  <div class="col-4" id="right-column">

  </div>

</div>